### ISSUE TITLE
Incorrect .eslintrc

### ISSUE THREAD

**Issue by Alpvax** [Trymunx/dragon-slayer#11]
https://github.com/Trymunx/vue-ds/blob/de3ea850df7c7e2dc6c25971d52e47241775ee57/.eslintrc.json#L13

Eslint expects 4-space indentation, but you have used 2 throughout your code.

**Comment by Alpvax** [comment]
Probably some other issues too, you really need to either remove it or fix it.

**Comment by Trymunx** [comment]
I fixed it with that commit, except I did it on GitHub so I didn't have a nice editor command to fix the indentation in the eslintrc.
