### ISSUE TITLE
Error moving to next map and back straight away

### ISSUE THREAD

**Issue by Alpvax** [Trymunx/Dragon-Slayer#2]
Moving a single tile away and back the error did not reoccur.
Might look into it some other time, busy right now.

Crash (with full path stripped to fit them on 1 line):
```Dragon-Slayer\js\src\GenerateMap.js:127
Uncaught TypeError: Cannot read property 'terrain' of undefined
    at genMap (Dragon-Slayer\js\src\GenerateMap.js:127)
    at Object.GS_GenerateMap.runState (Dragon-Slayer\js\src\GameStates\GS_GenerateMap.js:14)
    at EventEmitter.<anonymous> (Dragon-Slayer\js\src\GameStateManager.js:44)
    at emitOne (events.js:96)
    at EventEmitter.emit (events.js:191)
    at commandParse (Dragon-Slayer\js\src\GameStates\GS_OffPath.js:250)
    at HTMLInputElement.getInputAndParse (Dragon-Slayer\js\src\GameStates\GS_OffPath.js:83)
genMap @ Dragon-Slayer\js\src\GenerateMap.js:127
GS_GenerateMap.runState @ Dragon-Slayer\js\src\GameStates\GS_GenerateMap.js:14
(anonymous) @ Dragon-Slayer\js\src\GameStateManager.js:44
emitOne @ events.js:96
emit @ events.js:191
commandParse @ Dragon-Slayer\js\src\GameStates\GS_OffPath.js:250
getInputAndParse @ Dragon-Slayer\js\src\GameStates\GS_OffPath.js:83```

**Comment by Trymunx** [comment]
Thanks, it's an error with moving off the west side of the map, not to do with the speed at which you move. I am fairly sure it's something in this section of GenerateMap.js:
`case "east":
  position = (Math.round(RNG(sideLength)) * sideLength) - 1;
  break;
case "west":
  position = Math.round(RNG(sideLength - 1)) * sideLength;
  break;`
I think it's to do with the random number generator and the maths used there to find a position occasionally selecting one that is not part of the map, either -1 or 1 higher than the map's length.

**Comment by Trymunx** [comment]
Yeah it's 
`position = (Math.round(RNG(sideLength)) * sideLength) - 1;`
Can give a value of -1, I'll fix it soon.

**Comment by Trymunx** [comment]
Fix is changing that line to:
`position = (Math.round(RNG(1, sideLength)) * sideLength) - 1;`

**Comment by Trymunx** [comment]
Fixed.

**Comment by Alpvax** [comment]
Usual practice is to include this issue number in the commit when you close it

**Comment by Trymunx** [comment]
Is that #2 or is it listed elsewhere?

**Comment by Alpvax** [comment]
Exactly

**Comment by Alpvax** [comment]
I did that as an example of how it should be. If it wasn't already closed it would have closed it too

**Comment by Alpvax** [comment]
https://help.github.com/articles/closing-issues-using-keywords/
For more info

**Comment by Trymunx** [comment]
Cool, thanks for the link & example.
